routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'StaticPagesController@home');
Route::get('help', 'StaticPagesController@help')->name('help');
Route::get('about', 'StaticPagesController@about')->name('about');
Route::get('contact', 'StaticPagesController@contact')->name('contact');

Route::get('signup', 'UsersController@create')->name('signup');
Route::post('signup', 'UsersController@store');
Route::resource('users', "UsersController", ["except" => ["create", "store"]]);

Route::prefix('users')->group(function () {
    Route::get('{user}/following', "UsersController@following")->name("following");
    Route::get('{user}/followers', "UsersController@followers")->name("followers");
});

Route::get('login', "SessionsController@create")->name('login');
Route::post('login', "SessionsController@store");
Route::delete('logout', "SessionsController@destroy")->name('logout');

Route::get('account_activations/{token}/edit', "AccountActivationsController@edit")->name('activation');

Route::get('password_resets/create', "PasswordResetsController@create")->name("resets.create");
Route::post('password_resets', "PasswordResetsController@store")->name("resets.store");
Route::get('password_resets/{token}/edit', "PasswordResetsController@edit")->name("resets.edit");
Route::patch('password_resets/{token}', "PasswordResetsController@update")->name("resets.update");

Route::resource('microposts', "MicropostsController", ["only"=> ['store', 'destroy']]);

Route::resource('relationships', "RelationshipsController", ["only" => ['store', 'destroy']]);

resources/views/shared/error_messages.blade.php
@if ($errors->any())
<div id="error_explanation">
    <div class="alert alert-danger">
        The form contains {{ $errors->count() . str_plural('error', $errors->count()) }}.
    </div>
    <ul>
    @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
    </ul>
</div>
@endif

resources/views/shared/feed.blade.php
<ol class="microposts">
    @foreach ($feed_items as $micropost)
        @include("microposts.micropost")
    @endforeach
</ol>
{{ $feed_items->links() }}

resources/views/shared/micropost_form.blade.php
{{ Form::open(["route" => "microposts.store", 'files' => true]) }}
@include('shared.error_messages')
<div class="field">
    {{ Form::textarea('content', null, ["placeholder" => "Compose new micropost..."]) }}
</div>
{{ Form::submit("Post", ["class" => "btn btn-primary"]) }}
<span class="picture">
    {{ Form::file("picture", ["id" => "micropost_picture"]) }}
</span>
{{ Form::close() }}

<script type="text/javascript">
    $('#micropost_picture').bind('change', function() {
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5) {
        alert('Maximum file size is 5MB. Please choose a smaller file.');
      }
    });
</script>

resources/views/shared/stats.blade.php
@php empty($user) && $user = Auth::user() @endphp
<div class="stats">
    <a href="{{ route("following", $user->id) }}">
        <strong id="following" class="stat">
            {{ $user->following()->count() }}
        </strong>
        following
    </a>
    <a href="{{ route("followers", $user->id) }}">
        <strong id="followers" class="stat">
            {{ $user->followers()->count() }}
        </strong>
        followers
    </a>
</div>

resources/views/shared/user_info.blade.php
<a href="{{ route("users.show", Auth::id()) }}">{!! gravatar_for(Auth::user(), ["size" => 50]) !!}</a>
<h1>{{ Auth::user()->name }}</h1>
<span>{{ Html::linkRoute("users.show", "view my profile", Auth::id()) }}</span>
<span>{{ Auth::user()->microposts()->count() . " " . str_plural('micropost', Auth::user()->microposts()->count()) }}</span>